# Site settings
title: David Aguiar's Devblog
author: David Aguiar
email: davidaguiargonzalez@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Hi! I'm David and I'm a Software engineer especially passioned about Android and Java development. I hope you find my blog useful :) 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://siempredelao.github.com" # the base hostname & protocol for your site
permalink: /:title.html

twitter_username: PowerAndBrake
github_username:  siempredelao
google_play: 'dANDROvID'
google_plus_com: '109713158026546896626'  # Community link
google_plus_per: '110796575860407978413'  #Personal link
# facebook_app_id: 12345
linkedin: davidaguiargonzalez
stack_overflow: 1768231
analytics_id : 'UA-76423870-1'

# Layout settings
header_type: default  # values [ drawer, default ]
post_type: highlight    # values [ highlight, default ]
pagination_type: default  # values [ ops, default ]

share:
  twitter: true
  facebook: true
  google_plus: true
  linkedin: true

more_vert:
  option1:
    name: About me
    link: /about
  option2:
    name: Cookies policy
    link: /cookies
#   option3:
#     name: Cool Option 3   
#     link: www.myawesomelink.com

disqus: true
disqus_shortname: 'siempredelaogithubio'

# Build settings
markdown: kramdown
